### ISSUE TITLE
Facing Deep sleep issues on MI 10T

### ISSUE THREAD

**Issue by lebimax98** [NusantaraROM-Devices/device_xiaomi_apollopro#1]
Hey there, I installed this ROM about a week ago and it's pretty much working perfectly, except for this issue I have. For some reason the phone is not entering deep sleep mode reliably, even after 7 or 8 hours of no use.

At first I thought it could be an app problem, and while it did improve (by disabling GPS and wifi, and using the root version of YouTube Vanced) as you can see on the pictures below, I still lost about 30% during the night.

![Screenshot_20210713-090056_BBS](https://user-images.githubusercontent.com/42518324/125481325-5a5912dc-549f-44b2-8aa8-c5c68a673b49.png)

![Screenshot_20210713-092450_GSam_Battery_Monitor](https://user-images.githubusercontent.com/42518324/125481896-279bd17d-e03f-4cca-82a6-4cbdfe17fe52.png)

![Screenshot_20210713-092518_BBS](https://user-images.githubusercontent.com/42518324/125482050-1c45c563-9db7-49e7-81ae-8c70bfdeeee9.png)

![Screenshot_20210713-090159_BBS](https://user-images.githubusercontent.com/42518324/125482148-04818248-2ba1-450b-9e72-5b38ee549053.png)

Im using Nusantara 3.0
Thanks for the rom btw!

**Comment by goodmeow** [comment]
Smp2p bug deepsleep is coming from kernel as we found and we already notice that.
